### ISSUE TITLE
 ButtonLED example is not discovered on WB55

### ISSUE THREAD

**Issue by jmchiappa** [stm32duino/STM32duinoBLE#20]
Hello,
I've tried the ButtonLED peripheral example on a wb55 but I can't discovered it at all, even with the dongle or the nRFConnect application.
Is there a special thing to do before ?
Compilation is ok.

How to reproduce ?
1. Get a PNUCLEO wb55 board out of the box
2. open the ButtonLED from STM32duinoBLE/examples/Peripheral/ButtonLED
3. select PNucleo WB55
4. compile and flash
5. try to discover it with a nRF Connect application (GPS must be activated)

Framework : STM32duino 1.9.0
Arduino : 1.8.9
STM32duinoBLE : commit 60d26092cd8c419cea94df1ac911a0eb113f3534
STM32CubeProgrammer : 2.4.0

**Comment by fpistm** [comment]
Hi @jmchiappa 
To have the WB BLE functional you need the master of the core as it requires an updated clock config and some OTP config.
