### ISSUE TITLE
'BitOrder' was not declared in this scope

### ISSUE THREAD

**Issue by Stomper85** [stm32duino/STM32duinoBLE#33]
Zuvor kompilierte Datei wird verwendet: C:\Users\****\AppData\Local\Temp\arduino_build_674824\libraries\STM32duinoBLE\utility\ATT.cpp.o
C:\Users\****\OneDrive\Documents\Arduino\libraries\STM32duinoBLE\utility\HCISpiTransport.cpp: In constructor 'HCISpiTransportClass::HCISpiTransportClass(SPIClass&, BLEChip_t, uint8_t, uint8_t, uint8_t, uint32_t, uint8_t)':
C:\Users\****\OneDrive\Documents\Arduino\libraries\STM32duinoBLE\utility\HCISpiTransport.cpp:31:42: error: 'BitOrder' was not declared in this scope
   _spiSettings = SPISettings(frequency, (BitOrder)BLE_SPI_BYTE_ORDER, spi_mode);
                                          ^~~~~~~~
Bibliothek STM32duinoBLE im Ordner: C:\Users\****\OneDrive\Documents\Arduino\libraries\STM32duinoBLE (legacy) wird verwendet
Bibliothek SPI in Version 1.0 im Ordner: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI  wird verwendet
exit status 1

**Comment by fpistm** [comment]
Hi @Stomper85 
it seems you try to use this library with an avr core architecture:
`C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\SPI `

This library is for stm32 architecture as stated in the library.properties:
https://github.com/stm32duino/STM32duinoBLE/blob/4350cf09ec7e9d491b666e491f22e62541629111/library.properties#L9

You could try the official Arduino library: https://github.com/arduino-libraries/ArduinoBLE
but don't know if this will work as avr is not listed in the library.properties:
https://github.com/arduino-libraries/ArduinoBLE/blob/3e0cae6aef6bfb5369ef253566cca1dc9b0d9370/library.properties#L9
