### ISSUE TITLE
Zigbee support request

### ISSUE THREAD

**Issue by albertomercurio** [stm32duino/STM32duinoBLE#40]
Hello,

I don't know if this is the correct place for this issue. As an alternative I could write the issue in the Arduino_Core_STM32 repo.

Nevertheless, I think that the zigbee support could be an important implementation (some times more than the BLE protocol), since home automation makes more and more use of this protocol.

**Comment by fpistm** [comment]
Hi @albertomercurio 
This library is based on the official Arduino BLE one.
Goal was only to add the STM32 arch support. I guess you should open this request to this one then it could be inherited here after sync.
